### ISSUE TITLE
Items larger than 400K are attempted to be saved to the dynamo

### ISSUE THREAD

**Issue by jeffrichards** [revenuewire/dynamo-orm#2]
Dyanamo Item limit is 400KB as known from https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html

It would be good if the library checked that before save and issued an Exception in cases where the item is too big.  

Otherwise checking of that regard has to be done by each and every upstream use case that uses this library and might go over the limit.

It's not totally trivial to calculate the byte size of an object.  But I think it would be worth it all the same.

**Comment by cosmostail** [comment]
Hi Jeff, it is not bad idea but I'm afraid doing errors checking in ORM level will be a rabbit hole going forward. As item limit is just one of the restricts dynamodb has.  I would rather, just make the request to dynamodb, and fail in the upper stream as you mentioned. The result is the same (both will throw exceptions, cost a little to none), and it saves us a lot maintenance headaches.
